export const PIZZA_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PIZZA_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PIZZA_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const SWEET_LIST_REQUEST = "SWEET_LIST_REQUEST";
export const SWEET_LIST_SUCCESS = "SWEET_LIST_SUCCESS";
export const SWEET_LIST_FAIL = "SWEET_LIST_FAIL";

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL";
